services:
  - type: web
    name: cifar10-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: cifar10-data
      mountPath: /data
      sizeGB: 1 